[MultiDB] Add multidb support to sonic-ztp
Azure/sonic-ztp pull request #16
Opened 2020-06-06 18:24 UTC by rajendra-dendukuri

2020-06-06 18:26 UTC, rajendra-dendukuri commented
retest buster please

2020-06-10 03:27 UTC, wendani commented on src/usr/lib/ztp/ztp-profile.sh
> +            sonic-db-cli CONFIG_DB DEL "ZTP|mode"
May need to direct to `/dev/null` to avoid `sonic-ztp[xxx]: 1` in syslog

2020-06-10 04:00 UTC, rajendra-dendukuri commented on src/usr/lib/ztp/ztp-profile.sh
> +            sonic-db-cli CONFIG_DB DEL "ZTP|mode"
Thanks. I fixed it.

2020-06-25 11:27 UTC, lguohan commented
retest this please

2020-09-21 21:43 UTC, qiluo-msft commented on src/usr/lib/ztp/plugins/configdb-json
> +        if self.configDB is None:
>self.configDB [](start = 11, length = 13)

Could you clarify when it is None?

2020-09-21 21:49 UTC, qiluo-msft commented on src/usr/lib/ztp/plugins/configdb-json
> +                self.configDB.delete_table("ZTP")
>delete_table [](start = 30, length = 12)

Original code is deleting a entry, and new code is deleting a table. Is it expected?

2020-09-21 21:53 UTC, qiluo-msft commented on tests/test_configdb-json.py
> +        rc  = runCommand(cmd)
Could you just parse config-before.json, modify in memory and write to config-after.json?

2020-09-21 21:54 UTC, qiluo-msft commented on tests/test_configdb-json.py
> +        rc  = runCommand(cmd)
The same

2020-09-21 22:01 UTC, qiluo-msft commented on src/usr/lib/ztp/ztp-engine.py
> +    applDB   = None
You mixed using Class Variables and Instance Variables. Please check some tutorial, such as [https://careerkarma.com/blog/python-class-variables/](https://careerkarma.com/blog/python-class-variables/)

2020-09-21 22:07 UTC, qiluo-msft requested changes
As comments

2020-09-23 16:12 UTC, rajendra-dendukuri commented on src/usr/lib/ztp/plugins/configdb-json
> +        if self.configDB is None:
Fixed in latest commit

2020-09-23 16:12 UTC, rajendra-dendukuri commented on src/usr/lib/ztp/plugins/configdb-json
> +                self.configDB.delete_table("ZTP")
Fixed in latest commit

2020-09-23 16:12 UTC, rajendra-dendukuri commented on tests/test_configdb-json.py
> +        rc  = runCommand(cmd)
Fixed in latest commit

2020-09-23 16:13 UTC, rajendra-dendukuri commented on tests/test_configdb-json.py
> +        rc  = runCommand(cmd)
Fixed in latest commit

2020-09-23 16:13 UTC, rajendra-dendukuri commented on src/usr/lib/ztp/ztp-engine.py
> +    applDB   = None
Fixed in latest commit

2020-09-23 17:37 UTC, qiluo-msft commented
@dzhangalibaba Could you also help review this PR?

2020-09-23 17:48 UTC, qiluo-msft commented on src/usr/lib/ztp/plugins/configdb-json
> +        if self.configDB is None:
The new code seems worse. Why construct ConfigDBConnector twice?

---
In reply to: [492363061](https://github.com/Azure/sonic-ztp/pull/16#discussion_r492363061) [](ancestors = 492363061)

2020-09-23 18:14 UTC, rajendra-dendukuri commented on src/usr/lib/ztp/plugins/configdb-json
> +        if self.configDB is None:
My bad. I did not resolve the merge conflict properly and ended up having two copies of the code. I fixed it now.

2020-09-23 18:27 UTC, qiluo-msft approved these changes
LGTM. Please also resolve other reviewers' comments.

2020-09-23 18:37 UTC, dzhangalibaba requested changes

2020-09-23 18:37 UTC, dzhangalibaba commented on src/usr/lib/ztp/ztp-engine.py
> +                self.applDB = SonicV2Connector(host='127.0.0.1')
remove "host='127.0.0.1' " , it is not needed , all info should come from database_config.json and the host here didn't take effect.

2020-09-23 18:49 UTC, rajendra-dendukuri commented on src/usr/lib/ztp/ztp-engine.py
> +                self.applDB = SonicV2Connector(host='127.0.0.1')
Implemented the recommended change.

2020-09-23 20:19 UTC, dzhangalibaba approved these changes

2020-09-23 20:21 UTC, merged